pipeline {
    agent any

    environment {
        PYTHON = tool name: 'Python3', type: 'com.cloudbees.jenkins.plugins.python.PythonInstallation'
    }

    stages {
        stage('Preparar Entorno') {
            steps {
                script {
                    // Instala dependencias necesarias
                    sh "${env.PYTHON}/bin/pip install --upgrade pip"
                }
            }
        }

        stage('Enviar Correo') {
            steps {
                script {
                    // Ejecuta el script de Python
                    sh "${env.PYTHON}/bin/python enviar_correo.py"
                }
            }
        }
    }
}
