pipeline {
    agent any
    stages {
        stage('Preparar Entorno') {
            steps {
                script {
                    bat "python --version" // Verifica la versión de Python
                    bat "python -m pip install --upgrade pip" // Actualiza pip
                }
            }
        }

        stage('Ejecutar Script de Python') {
            steps {
                script {
                    bat "python enviar_correo.py" // Ejecuta el script de Python
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline ejecutado con éxito. ✅"
            emailext (
                subject: "Pipeline Exitoso: ${env.JOB_NAME}",
                body: "El pipeline ha sido ejecutado con éxito en ${env.BUILD_URL}.",
                recipientProviders: [[$class: 'DevelopersRecipientProvider']]
            )
        }
        failure {
            echo "El pipeline ha fallado. ❌"
            emailext (
                subject: "Pipeline Fallido: ${env.JOB_NAME}",
                body: "El pipeline ha fallado. Revisa los logs en ${env.BUILD_URL} para más detalles.",
                recipientProviders: [[$class: 'DevelopersRecipientProvider']]
            )
        }
    }
}
